.gitignore, datahost-ld-openapi/deps.edn, datahost-ld-openapi/env/test/resources/test-base-system.edn, datahost-ld-openapi/resources/ldapi/base-data.trig, datahost-ld-openapi/resources/ldapi/base-system.edn, datahost-ld-openapi/src/tpximpact/datahost/ldapi/native_datastore.clj, datahost-ld-openapi/test/tpximpact/ldapi_test.clj, datahost-ld-openapi/test/tpximpact/native_datastore_test.clj, datahost-ld-openapi/test/tpximpact/test_helper.clj
Addresses issue https://github.com/Swirrl/catql-prototype/issues/23
=> Add simple rdf4j native store

datahost-graphql/resources/catql/base-system.edn, datahost-graphql/src/tpximpact/catql.clj
Addresses issue https://github.com/Swirrl/datahost-prototypes/issues/11
=> Add facet labels lookup and resolve labels

datahost-graphql/test/tpximpact/test_helpers.clj
Remove leftovers from test code.
=> Remove debug code

datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/copy.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/release.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/series.clj
This is just some initial shuffling of route config in preparation for adding the releases routes. Merging now to avoid conflicts with other in progress work on the ld api.
=> Release endpoints skeleton

.gitignore, datahost-graphql/env/docker/resources/catql/env.edn, datahost-graphql/src/tpximpact/sys.clj, datahost-ld-openapi/env/test/resources/test-system.edn, datahost-ld-openapi/resources/ldapi/base-system.edn, datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj, datahost-ld-openapi/src/tpximpact/datahost/sys.clj, datahost-ld-openapi/test/tpximpact/datahost/ldapi/series_test.clj, datahost-ld-openapi/test/tpximpact/test_helpers.clj
Database was not being cleaned up. Improved system loading and test helpers.
=> LD API duratom db test cleaning fixes

datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/series.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/shared.clj
This PR does not change any functionality - it's a purely "cosmetic" change; renames a function and adds some doc strings.
=> refactoring: more appropriate names shared util functions

datahost-ld-openapi/deps.edn, datahost-ld-openapi/src/tpximpact/datahost/ldapi/errors.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/shared.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj
Addresses issue https://github.com/Swirrl/datahost-prototypes/issues/124
=> LD API: Add generic error handlers

datahost-ld-openapi/deps.edn, datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/revision.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/shared.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/revision.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/strings.clj, datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_test.clj, datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
Addresses issue https://github.com/Swirrl/datahost-prototypes/issues/116
=> LD API: Create and retrieve revisions for releases

datahost-ld-openapi/deps.edn, datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/revision.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/revision.clj, datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
Addresses issue https://github.com/Swirrl/datahost-prototypes/issues/119
=> LD API Revision: return contents as CSV when accept header "text/csv"

doc/data-model.md
This PR updates the data model to reflect the latest agreed version.
There is also a [document here](https://docs.google.com/document/d/1Ld3KDjfYwOdLaRn8fJkEVcg1oW61uqGOSmLBfCSd7mQ/edit) with an ongoing discussion of the latest concerns and decision points for the post-prototype API.
=> Update model entities to remove commits and add schemas

datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/revision.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/release.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/revision.clj, datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
=> LD API: GET entire Release contents as CSV

datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj, datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
Addresses issue https://github.com/Swirrl/datahost-prototypes/issues/147.
/cc @robchamberspfc
=> Fix Revision ID auto-increment bug

datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/revision.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/revision.clj, datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
=> GET Change contents as CSV

datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj, datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
Test are broken becuase this PR is against a WIP branch that also has broken tests right now.
=> New Revision IDs are scoped to parent Release in triplestore

datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj, datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj, datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/series_test.clj
Addresses issue #161.
/cc @robchamberspfc
=> Fix: description should be OPTIONAL on Releases & Series

datahost-ld-openapi/doc/decision-log.md
Starting a document to record decisions we make in meetings etc. to keep track as a reference point for everyone.
=> Add decision log doc

datahost-ld-openapi/deps.edn, datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/json_ld.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/revision.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/series.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/store/triplestore.clj, datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_test.clj, datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj, datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/series_test.clj, datahost-ld-openapi/test/tpximpact/test_helpers.clj
=> Get all series, releases, revisions

datahost-ld-openapi/doc/data-model-definitions.md
Adds a document defining the concepts used in our data model.
=> Documentation:  data model definitions

datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
Another little refactoring to use Matcha calls to load resources: in this case a `Release`.
=> Further handler query refactorings

datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/release.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/revision.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/series.clj
Resolves https://github.com/Swirrl/datahost-prototypes/issues/186
=> LD API: Set JSON-LD content-type on appropriate API responses

datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_test.clj
No issue number was created for this problem.
=> LD API: Fix flakey test - truncated precision in JSON datetime

datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj
Now that the API is returning the correct JSON-LD content-type from handler calls, an issue has cropped up where some users were enjoying the convenience of looking at an API GET route within a browser window. In the past the handlers were sending a default content-type of `application/json`, so the browser knew that it could simply render the data to the user.
This PR adds a new middleware affordance which attempts to detect an in-browser GET request,  and if detected, the `application/json+ld` `content-type` from API response will be overridden so that the browser renders the response as plain JSON ( `application/json` ) and does not attempt to download the unrecognized `application/json+ld` content as a file.
=> LD API: Add browser render middleware content-type affordance

datahost-ld-openapi/src/tpximpact/datahost/ldapi/files.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/middleware.clj
=> minor fixes and cleanups

datahost-ld-openapi/env/test/resources/test-inputs/revision/2021-deletes.csv, datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/revision.clj, datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
This PR works towards satisfying  https://github.com/Swirrl/datahost-prototypes/issues/83. More to follow.
=> API: refactor routes; add change kind parameter to change routes

datahost-ld-openapi/.gitignore, datahost-ld-openapi/bin/hurl-data/change1.csv, datahost-ld-openapi/bin/hurl-data/change1.meta.json, datahost-ld-openapi/bin/hurl-data/change2.csv, datahost-ld-openapi/bin/hurl-data/test-schema.json, datahost-ld-openapi/bin/hurl-data/test.hurl.template, datahost-ld-openapi/bin/hurl-test, datahost-ld-openapi/src/tpximpact/datahost/ldapi/errors.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/middleware.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/release.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/revision.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/series.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/shared.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/util/data_validation.clj
Minor changes. Most of the updated files are not code - just test helpers and data.
The most notable changes:
- middleware order [change](https://github.com/Swirrl/datahost-prototypes/pull/236/commits/2cd9fa056b45552824c1a3549aefc2d24d23b7f9)
- small cleanup in 404 responses (e.g. returning JSON when requested)
=> ldapi: minor changes, test utilities

datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
'appends' used to be a File, but now it's a stream and we consume it multiple times (worked with a File, not with an InputStream).
=> ldapi: fix post-change - reset stream after validation

datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/middleware.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/revision.clj, datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/shared.clj, datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
=> ldapi: use content-type as the change format

datahost-ld-openapi/.gitignore, datahost-ld-openapi/env/test/resources/test-system.edn, datahost-ld-openapi/resources/ldapi/base-system.edn
=> Change DB director location to ./tmp

.circleci/config.yml
Adding the UI wireframe in consumer-wireframes to circleci. Circleci will build the wireframe and then save a cache of dependancies for future builds.
=> Build UI prototype in CI
