- datahost-ld-openapi/doc/datahost-ontology.ttl
- datahost-ld-openapi/env/test/resources/test-inputs/release/metadata-1.json
- datahost-ld-openapi/resources/jsonld-context.json
- datahost-ld-openapi/src/tpximpact/datahost/scratch/release.clj
- datahost-ld-openapi/src/tpximpact/datahost/scratch/release/changeset.clj
- datahost-ld-openapi/src/tpximpact/datahost/scratch/release/revision.clj
- datahost-ld-openapi/src/tpximpact/datahost/scratch/release/schema.clj
- datahost-ld-openapi/src/tpximpact/datahost/scratch/series.clj
- datahost-ld-openapi/test/tpximpact/datahost/scratch/model_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/scratch/series_test.clj
The tests all pass so this can be merged if we want.
It’s still all in the scratch namespace in the source tree, so it’s not integrated with the http layer, so is relatively independent from the rest of the code.
It does however define a bit more of the shape regarding dataset-series and releases (and hints towards the future with schemas attached to releases, and some small sketch work on changesets).
But the main thing that’s getting closer are dataset-series and release entities.
The main other relevant thing is that I’ve written some tests defining expectations around constructing a series and a release within it:
https://github.com/Swirrl/datahost-prototypes/blob/49ee1d326f65db7f3c564f9d20fa2783050bd399/datahost-ld-openapi/test/tpximpact/datahost/scratch/model_test.clj#L33-L69
The …
> Scratch work sketching out more of the data model

- datahost-graphql/src/tpximpact/catql.clj
- datahost-graphql/src/tpximpact/catql/search.clj
- datahost-graphql/test/tpximpact/facet_search_test.clj
Fixes: #8 
Main update is in Lacinia's `facets-resolver` fn which needs to index the received data to set the 'enabled' flag. Since this is still a prototype, I did not pay much attention to performance (we're querying the datasets twice anyway atm, I have not changed that).
> fix: facet search

- .gitignore
- datahost-ld-openapi/resources/ldapi/base-system.edn
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/series.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/util.clj
- datahost-ld-openapi/src/tpximpact/datahost/scratch/release.clj
- datahost-ld-openapi/src/tpximpact/datahost/scratch/series.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/series_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/scratch/model_test.clj
- datahost-ld-openapi/test/tpximpact/ldapi_test.clj
- datahost-ld-openapi/test/tpximpact/native_datastore_test.clj
- datahost-ld-openapi/test/tpximpact/test_helpers.clj
This integrates the work making series work into the api/integrant system. There are routes for `put`-ing and `get`-ing datasets, the data is currently stored in a configured duratom, and key type (i.e. string vs keyword etc) is preserved round-trip.
Closes #51 
Closes #25
> Integrating handlers

- datahost-graphql/src/tpximpact/catql/schema.clj
- datahost-graphql/test/tpximpact/facet_search_test.clj
- datahost-graphql/test/tpximpact/test_helpers.clj
Query that does not specify `datasets` field hangs, because the query waits for the `promise<datasets>` promise in the facets resolver (which will never be delivered in this case).
Fixed by inspecting context's selection and delivering empty datasets value.
> fix: ensure query doesn't hang when `datasets` field not specified

- datahost-graphql/env/dev/src/dev.clj
- datahost-graphql/env/dev/src/user.clj
- datahost-graphql/env/docker/resources/catql/env.edn
- datahost-graphql/resources/catql/base-system.edn
- datahost-graphql/src/tpximpact/catql.clj
- datahost-graphql/src/tpximpact/catql/http.clj
- datahost-graphql/src/tpximpact/catql/query.clj
- datahost-graphql/src/tpximpact/catql/schema.clj
- datahost-graphql/src/tpximpact/sys.clj
- datahost-graphql/test/tpximpact/facet_search_test.clj
- datahost-graphql/test/tpximpact/test_helpers.clj
- shared-deps/deps.edn
This is for the GraphQL catalog service. I will do the same for the LD API service sub-project in a follow-up PR.
- `(reset)` in the REPL now works as expected - namespaces with code changes will be reloaded.
- `dev` namespace does not call `main` to start the system.
> Proper Integrant use with namespace reloading

- deploy/terraform/graphql/.terraform.lock.hcl
- deploy/terraform/graphql/main.tf
Issue #91 - Add AWS provider and define a route53 DNS record for the GraphQL prototype pointing to the datahost server address.
> Create DNS record for GraphQL prototype

- datahost-ld-openapi/env/dev/src/dev.clj
- datahost-ld-openapi/env/dev/src/user.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/jetty.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/native_datastore.clj
- datahost-ld-openapi/src/tpximpact/datahost/sys.clj
- datahost-ld-openapi/test/tpximpact/test_helpers.clj
This is for the LD API catalog service. GraphQL service has already been revised for reloading.
- `(reset)` in the REPL now works as expected - namespaces with code changes will be reloaded.
- dev namespace does not call main to start the system.
> LD API service: Proper Integrant use with namespace reloading

- deploy/terraform/gcloud/swirrl-ons-datahost/main.tf
- deploy/terraform/graphql/main.tf
Issue #32 - Add HTTP(S) load balancers in front of the datahost server and update the DNS to point to it instead of the server.
Add the CircleCI service account to the compute.loadBalancerAdmin role so it can create and update load balancer components.
> Create load balancer for datahost server

- datahost-graphql/resources/catql/catalog.graphql
- datahost-graphql/src/tpximpact/catql/schema.clj
- datahost-graphql/test/tpximpact/facet_search_test.clj
The search string was not taken into consideration when setting the `enable` field on facets.
I updated the `make-facet` to use the search string and added appropriate tests.
Fixes #65
> Search string argument in faceted search

- .circleci/config.yml
- datahost-ld-openapi/build.clj
- deploy/terraform/ldapi/environments/dev/.terraform.lock.hcl
- deploy/terraform/ldapi/environments/dev/main.tf
- deploy/terraform/ldapi/environments/dev/variables.tf
- deploy/terraform/ldapi/modules/env/main.tf
- deploy/terraform/ldapi/modules/env/variables.tf
- deploy/terraform/ldapi/modules/load_balancer/main.tf
- deploy/terraform/ldapi/modules/load_balancer/variables.tf
- deploy/terraform/ldapi/modules/server/main.tf
- deploy/terraform/ldapi/modules/server/outputs.tf
- deploy/terraform/ldapi/modules/server/variables.tf
Closes #108 - Define Terraform modules to define an environment for the ld-openapi application. This follows a similar structure to the graphql application:
* server module to define the server
* load_balancer module for the load balancer
* env module to define the entire environment
Update the CI build to automatically deploy the latest version to the `dev` environment for builds on the `main` branch.
> Create Terraform definition for ld-openapi application

- datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/release.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/series.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/shared.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/release.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/series.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/shared.clj
- datahost-ld-openapi/src/tpximpact/datahost/scratch/release.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/series_test.clj
Another small change, just extracting more shared things as releases are implemented but want to merge sooner rather than later in the interest of reducing merge conflicts.
> Shuffle shared route and model helpers into shared places

- datahost-ld-openapi/deps.edn
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/router_test.clj
Issue #90 - Add ring-cors middleware dependency. Add a CORS middleware which applies this to all routes allowing cross-origin requests from all origins.
> Add middleware implementing the CORS protocol for all routes

- datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/series.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/shared.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/util.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/series_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/scratch/model_test.clj
Documents should have `dcterms:modified` and `dcterms:issued` entries.
Achieving the above is simple, but requires extra handling to ensure:
- client can't update `dcterms:issued`
- client can't overwrite the existing document with empty document
- proper handling of `{}` and `nil` input documents
> Include  'dcterms:issued' and 'dcterms:modified' in documents

- datahost-ld-openapi/env/test/resources/test-system.edn
- datahost-ld-openapi/src/tpximpact/datahost/sys.clj
In addition to `#env`, I also through in a few other readers that we tend to need in other projects e.g. `#uri`, `#int`, a naive `#or`, `#resource`, `#regex`.
> LD API: add env config reader

- .gitignore
- datahost-ld-openapi/deps.edn
- datahost-ld-openapi/env/test/resources/test-system.edn
- datahost-ld-openapi/resources/ldapi/base-system.edn
- datahost-ld-openapi/src/tpximpact/datahost/ldapi.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/release.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/schema.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/series.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/shared.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/release.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/series.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/schemas/api.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/schemas/common.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/schemas/release.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/schemas/series.clj
- datahost-ld-openapi/src/tpximpact/datahost/sys.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/series_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/test_util/http_client.clj
- datahost-ld-openapi/test/tpximpact/datahost/scratch/model_test.clj
- datahost-ld-openapi/test/tpximpact/ldapi_test.clj
- datahost-ld-openapi/test/tpximpact/test_helpers.clj
Recent PR added `dc:issued` and `dc:modified` fields to series. This PR extends that change to releases.
Most important changes:
- extracted the common logic for timestamps
- new namespace prefix: *.datahost.ldapi.schemas - for common schemas
- logic for inferring upsert  (located in `t.d.ldapi.models.shared`)
- move [series|release]-key ctors out of update fns - they rely on hardcoded URI
- remove potential race condition on when returning http status (the existing code did a 'check then do')
-  we now rely on a status stored in the metadata of the atom value
- data readers to pull environment variables into integrant configuration (by @scottlowe)
- integrant config for a test HTTP client - no more using hardcoded port
> Release timestamps

- deploy/terraform/graphql/modules/env/main.tf
- deploy/terraform/graphql/modules/server/main.tf
- deploy/terraform/ldapi/modules/env/main.tf
- deploy/terraform/ldapi/modules/server/main.tf
Include a prefix of the graphql and ldapi container image digests in the corresponding server names. This ensures they will be re-created and added to the load balancer. Previously, the server names remained the same and had a lifecycle dependecy on a null resource containing the image digest. Terraform fails to detect any changes in the load balancer configuration in this case, so the new server is not re-added to the load balancer on construction.
> Include container image digests in server names

- datahost-ld-openapi/doc/data-model-example.ttl
- datahost-ld-openapi/env/test/resources/test-inputs/release/metadata-1.json
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/change.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/release.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/revision.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/shared.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/scratch/model_test.clj
This PR is mostly just changing Relase routes and DB keys from `/release/` to `/releases/`.
It also fixes the object value for the `dh:appliesToRelease` predicate to point at a proper Release URI instead of `../release-id`.
`dcat:inSeries` predicate also now points to a proper REST route and DB key.
/cc @robchamberspfc
> Consistency in Release URLs, DB keys, routes & inverse triples.

- datahost-ld-openapi/deps.edn
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/release_schema.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/shared.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/copy.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/release.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/shared.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/schemas/release_schema.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_schema_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/series_test.clj
- datahost-ld-openapi/test/tpximpact/test_helpers.clj
Adding/Retrieving release schemas.
- add API endpoints to GET & PUT schema
- adding a schema updates the associated release with a reference to the schema (key: `datahost:hasSchema`)
Closes #79
> Add Release schemas

- datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/revision.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
For the Revision GET route, one has to currently supply an `accepts` header, even if you'd like the default JSON, rather than CSV returned. This is because I couldn't get to the bottom of a coercion exception issue last week.
This patch disables coercion for this route.
/cc @robchamberspfc
> Revisions CSV / JSON format: Fix for default JSON format

- datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/shared.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/util/collections.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/util/rdf.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/series_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/scratch/model_test.clj
Slight code organisation change: split the `tpximpact.datahost.ldapi.util`  namespace into separate namespaces under shared prefix to avoid a grab bag of random functions.
> ld-openapi: split 'util' into distinct namespaces

- datahost-ld-openapi/env/docker/resources/ldapi/env.edn
- datahost-ld-openapi/env/test/resources/test-system.edn
- datahost-ld-openapi/resources/ldapi/base-system.edn
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/files.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/revision.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/release.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/revision.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/store.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/store/file.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/store/triplestore.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/series_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/router_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/store/file_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/store/temp_file_store.clj
- deploy/terraform/ldapi/modules/server/main.tf
Issue #152 - Add a ChangeStore protocol for storing and retrieving CSV change data. Move the existing implementation into the new store.triplestore namespace, and add a store.file implementation which stores change files on the filesystem. Files are stored in the file store in a location determined by the SHA-1 hash of their contents.
Update the change and revision handlers to require an implementation of the change store used to save and retreive change data. The key returned by the insert-append method is associated with the change (currently only append) record in the triplestore.
Add a test implementation of the file store in store.temp-file-store which deletes the file store directory on close. Define an integrant componemt which deletes the directory in the halt-key! method.
Update …
> Add ChangeStore protocol for storing change data

- datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
We generate new id (an int) for a change but we currently do only an unsafe check if a change is already associated with the revision. To ensure correctness we should do a conditional insert using a transaction. `NativeStore` and `MemoryStore` support transactions.
> LDAPI: Allow only 1 change per revision using transaction

- datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_schema_test.clj
Issue #193 - Fix db/schema->response-body to handle schemas with a single column. When schemas have a single column, the dh:columns key contains a string instead of a single-element collection. Lift non-collection values into a single-valued collection before further processing.
Extract parsing the column number into its own function.
> Fix inlining for schemas with a single column

- datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/shared.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/release.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_schema_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
We no longer allow the user to specify the schema-slug; the schema is always accessible under `.../releases/$RELEASE/schema` path. 
Closes #166
> Stop requiring schema-id (slug)

- .circleci/config.yml
- datahost-ld-openapi/build.clj
Issue #175 - Add an optional :to parameter to the docker build task which controls how built images are published. Only publish images to the public swirrl repository if this is set to :remote.
Update the deploy-ld-openapi-service CI task to supply this option so containers are published.
Add documentation to the docker task.
> Make image publishing optional in the docker build task

- datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/shared.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/middleware.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/release.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/revision.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/series.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/shared.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/schemas/common.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/series_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/router_test.clj
Our current request parameter validation is inconsistent and allows creation of resources with missing fields. This PR fixes that by being more strict about the headers, body and query parameters. 
Summary:
- moved content-type verification to a middleware to stop processing request without set content-type
- middleware for verifying the existence of a resource (we can refactor some of our handlers to make use of it)
- middleware for validating params depending on whether it's an update or insert
- updated tests
Closes Issue #189
> ldapi: more consistent param validation when creating or updating resources

- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/revision.clj
The recently introduced middleware is configured incorrectly for Changes - it checks for existence of Revision.
This PR fixes the config and adds a `resource-exists?` for Revision checks.
> ldapi: check for change, not revision, 404 on missing revision

- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/release.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_schema_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
This addresses #195 
As an implementation it works. However, I still need to figure out and retro-fit schema validation on the multipart file upload payload itself, which I don't think we can do at the top level because the file contents is a JSON string at that point. Still thinking about this.
> API: Upload schema as file rather than request body

- datahost-ld-openapi/doc/data-model-definitions.md
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/shared.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/revision.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/shared.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/util/data_compilation.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/util/data_validation.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/util/data_compilation_test.clj
We allow uploads of appends/retractions in CSV format. Those changes should be compiled into a single dataset for each revision. This PR introduces new namespace that provides such functionality. It does _not_ plug it into the relevant handlers yet.
- new functionality in the `tpximpact.datahost.ldapi.util.data-compilation` ns. Relying on tablecloth's functionality.
- renamed :dh/appends to :dh/updates
- added :dcterms/format to triple to changes
Also:
- [remove flag-resource-exists middleware from changes](https://github.com/Swirrl/datahost-prototypes/pull/213/commits/b3e85c606ec04e41f6b46721c415f125b081e728)
Closes #190
> Compile all appends and deletes into a complete download

- datahost-ld-openapi/README.md
- datahost-ld-openapi/doc/data-model-definitions.md
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/middleware.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/release.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/shared.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/util/data_validation.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/test_util/http_client.clj
I removed the JSON input validation when we switched from submitting the Release schema JSON from request body to file upload.
Now that I've figured out how to get validation working on the JSON string content of the file upload itself, I've reinstated the validation call.
Bonus: Fixed some typos and minor issues.
> API: Reinstate Release LD schema input validation in handler

- datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/store.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/store/file.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/util/data_compilation.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/util/data_validation.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/store/file_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/store/temp_file_store.clj
Relatively minor refactoring in preparation for https://github.com/Swirrl/datahost-prototypes/issues/182
Summary of changes
- renaming a lot of occurrences of 'append' to 'update'
- extending the `ChangeStore` interface to avoid doing repeated file reads (one for calculating the checksum, one for parsing the CSV)
> ldapi: naming changes, ChangeStore protocol changes

- datahost-ld-openapi/deps.edn
- datahost-ld-openapi/env/auth/resources/ldapi/env.edn
- datahost-ld-openapi/resources/ldapi/base-system.edn
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/secrets.clj
- deploy/terraform/ldapi/modules/server/main.tf
Use google secrets as a method to manage the basic auth secret.
NOTE: Before merge/deploy, we need to test the running instance & container's access to secret manage.
Use the google secrets API directly in application code, using the `gcloud` java library.
Can run same code locally as in prod. Doesn't leave env vars or config with secrets lying around. Recommended by Google.
App has a startup dependency on google secrets API. Though any other method that does not supply the secret to the compiled artifact, loading the secret at runtime, has the same dependency.
Adds complexity to the dev environment to run this code (it doesn't run in dev/test usually). The user's environment must have gcloud credentials setup, and the user must have access to the secretmanager.
The system running this …
> Manage basic auth as google secret

- datahost-ld-openapi/env/test/resources/test-system.edn
- datahost-ld-openapi/src/tpximpact/datahost/system_uris.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_schema_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/series_test.clj
- datahost-ld-openapi/test/tpximpact/test_helpers.clj
More work addressing  [Make base URI configurable#216](https://github.com/Swirrl/datahost-prototypes/issues/216)
and relates to previous PR https://github.com/Swirrl/datahost-prototypes/pull/221.
> Alternative RDF base URI in test base

- datahost-ld-openapi/resources/ldapi/base-system.edn
- datahost-ld-openapi/src/tpximpact/datahost/ldapi.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj
More work addressing https://github.com/Swirrl/datahost-prototypes/issues/216
and relates to previous PRs https://github.com/Swirrl/datahost-prototypes/pull/221 & #224.
I do not plan to enable set the `:tpximpact.datahost.ldapi/base-path` key to a non empty string value at present, because some of the tests use hard-coded paths that would break. I will do some follow-up work to alter those tests.
> API: Add application base path (or mount point) to router and requests

- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/series_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/test_util/http_client.clj
Because if the code under test doesn't throw (E.G., a 200) then the assertions are never run and so don't fail.
> Don't try catch http requests in tests

- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/shared.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/router_test.clj
Closes: #219 
This PR implements (empty) csv metadata as per the spec[1], by:
- Adding a Link header to csvs for releases and revisions, to point to the json metadata file for the csv. (at `{csv-url}-metadata.json`)
- Adding a placeholder json metadata file at the url `{csv-url}-metadata.json`, where a resource at `{csv-url}` exists.
- Adding a metadata URI pattern spec at `/.well-known/csvm`. (though according to spec this is redundant)
[1] https://www.w3.org/TR/2015/REC-tabular-data-model-20151217/#locating-metadata
> Add csvm handlers for release & revisions

- datahost-ld-openapi/env/test/resources/test-system.edn
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers/internal.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/middleware.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/release.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/revision.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/schemas/common.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/store.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/store/file.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/util/data_compilation.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/util/data_validation.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/util/triples.clj
- datahost-ld-openapi/src/tpximpact/datahost/system_uris.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/series_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/store/temp_file_store.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/util/data_compilation_test.clj
To enable instantenaous CSV downloads, we want to generate the dataset snapshot when a 'change' is added to the a revision. There's no job queue/worker threads/etc, so the work will happen in the request handler. 
- uploading a change (append|retraction) causes an append/retraction to previous revision's CSV snapshot.
- the dataset needs to fit into memory - we just rely on tablecloth's datasets and manipulate them in memory.
- when such the revision is not tagged with a snapshot (key to the ChangeStore) - we throw
- snapshot CSVs are stored in the ChangeStore - I don't see any reasons why the snapshots should be stored separately from changes
- more utility middleware: e.g. creating often used URIs from path params
- replaced occurrences of `datahost.change.kind/*` with `:dh/ChangeKind*` …
> ldapi: create snapshot CSV on ingest

- datahost-ld-openapi/doc/data-model-example.ttl
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/middleware.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/release.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/revision.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/series.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_schema_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
- datahost-ld-openapi/test/tpximpact/test_helpers.clj
Fix: #233 
This PR fixes a fundamental issue with the way that certain POST requests were being handled and tested.
An HTTP request has (in short) headers & message body. If the request is a multipart request, the multiple parts sit in the message body. Ring (and reitit) parse the request, and can have keys `:body` and `:multipart-params`, however a valid HTTP request can never produce a Ring request that has _both_ a `:body` and `:multipart-params`.
The tests were passing both keys, and the handlers were handling both keys, but were not forming a valid HTTP request, rather passing an invalid request directly into the root handler.
When a user, via swagger or otherwise, tries to form such a request it cannot work.
The tests have been fixed to make an actual HTTP request with clj-http, …
> Fix use of multipart requests and message body in HTTP POST (changes)

- datahost-ld-openapi/env/test/resources/test-system-base-path.edn
- datahost-ld-openapi/resources/ldapi/base-system.edn
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/router_test.clj
- datahost-ld-openapi/test/tpximpact/native_datastore_test.clj
- datahost-ld-openapi/test/tpximpact/test_helpers.clj
Follow on work from PR https://github.com/Swirrl/datahost-prototypes/pull/221.
I have returned from holiday and this is the PR to add tests to ensure that the alternative request base path configurations worked - well they didn’t! I have fixed this issue now in a draft PR that I’m still working on
It turns out that setting the Ring context in middleware to work as a context for a base path in routing doesn’t work with Reitit in Datahost the same as it works in muttnik. I had assumed that Reitit would do the “right thing” with this information from the Ring request.
Regardless, even if Reitit did look at the request `:context`, the other reason the middleware wasn’t working correctly is because Reitit is optimised for speed as a “routing first” router, so the middleware is not hit before a …
> API: revise base-path middleware to work properly with reitit; add test

- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/shared.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
Summary: Some predefined explainers used by the `validate-creation-body+query-params` middleware weren't really explainers (missing `malli.core/explainer` call).
Closes #232
> ldapi: fixes revision creation with query params only

- datahost-ld-openapi/bin/hurl-data/test.hurl.template
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
We have the following routes
```
POST /data/.../:revision-id/changes
GET  /data/.../:revision-id/changes/:change-id
POST /data/.../:revision-id/deletes
```
(And I'm about to add a `POST .../corrections`)
- Each change has a 'kind' associated: append/retraction/correction.
- Each change gets an URI matching `/data/.../:revision-id/changes/:change-id` (note the 'changes' part, the URI no longer carries information about the 'kind').
This PR renames two routes to be consistent with our internal naming (`:datahost.change/kind` -> `#{:dh/ChangeKindAppend :dh/ChangeKindRetract}`):
```
POST /data/.../:revision-id/appends
POST /data/.../:revision-id/retractions
```
This would leave us with `GET .../changes`. The only issue is we don't allow getting the metadata of a change (only CSVs at the …
> ldapi: rename change releated routes

- datahost-ld-openapi/bin/hurl-data/change2.csv
- datahost-ld-openapi/bin/hurl-data/change2.meta.json
- datahost-ld-openapi/bin/hurl-data/change3.csv
- datahost-ld-openapi/bin/hurl-data/change3.meta.json
- datahost-ld-openapi/bin/hurl-data/test-schema.json
- datahost-ld-openapi/bin/hurl-data/test.hurl.template
- datahost-ld-openapi/env/test/resources/test-inputs/revision/2021-corrections.csv
- datahost-ld-openapi/env/test/resources/test-inputs/schemas/simple.json
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers/internal.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/revision.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/schemas/common.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/util/data_compilation.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/util/data_validation.clj
- datahost-ld-openapi/src/tpximpact/datahost/uris.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/util/data_compilation_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/util/data_validation_test.clj
There are now three change related endpoints:
- '.../appends',
- '.../retractions'
- '.../corrections'
This change deals with the last one. Each of those endpoints accepts a plain CSV. _Plain_ in this context means that it does not include any extra metadata columns. We identify rows by hashing values according to the release schema (all schema columns except the measure column).
The generated snapshot CSVs also don't contain any extra columns.
Additionally: the 'appends' operation now ensures we don't have duplicate rows hashes (we choose the first occurring value, if user wants the later occurring one, they probably want a 'correction').
I've used Murmur hash as the hashing algorithm, as we already have `org.apache.commons.codec.digest.*` in our deps.
Fixes #218
> ldapi: uploading and applying corrections

- datahost-ld-openapi/deps.edn
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/util/data_compilation.clj
Murmur3 is not suitable for this. Switching to [Zero-Allocation-Hashing](https://github.com/OpenHFT/Zero-Allocation-Hashing/) library.
> ldapi: use different hashing function to identify rows

- datahost-ld-openapi/deps.edn
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/series.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/store.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/store/file.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/client/ring.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/resources.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/series_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/store/temp_file_store.clj
Fixes #155 - Add DELETE route for series which deletes the route along with all child resources (releases, revisions etc.). Also deletes any changes within the change store only referenced by the deleted series.
> Delete series and all child resources

- .circleci/config.yml
- deploy/terraform/graphql/environments/dev/main.tf
- deploy/terraform/graphql/environments/ons/.terraform.lock.hcl
- deploy/terraform/graphql/environments/ons/main.tf
- deploy/terraform/graphql/environments/ons/variables.tf
- deploy/terraform/graphql/modules/load_balancer/main.tf
- deploy/terraform/ldapi/environments/dev/main.tf
- deploy/terraform/ldapi/environments/ons/.terraform.lock.hcl
- deploy/terraform/ldapi/environments/ons/main.tf
- deploy/terraform/ldapi/environments/ons/variables.tf
Issue #254 - Change the hosts for the ldapi and graphql servers within their respective dev environments.
Use the module parameters to set the domain name within the graphql load balancer module.
> Change domain for ldapi and graphql dev environments

- datahost-ld-openapi/src/tpximpact/datahost/ldapi/compact.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/json_ld.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/shared.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/schemas/common.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/series_test.clj
This issue adds the extra metadata fields that Rob [requested in this doc](https://docs.google.com/spreadsheets/d/1YB6O3icfqKuW_BF4rb8dqnjZT0hNtpLJJ1MP3NO2TIg/edit#gid=0).
Note the predicates are added pretty fast-and-loose here. We would want to standardize/agree these if we were proceeding for real. For now this accomplishes the goal of allowing users to attach extra information to each resource. The new predicates that are "coined" as a result of this pr are (where `:dh` is `https://publishmydata.com/def/datahost/`):
`:dh/nextUpdate`
`:dh/relatedLinks`
`:dh/contactName`
`:dh/contactEmail`
`:dh/contactPhone`
`:dh/publicationDate`
`:dh/reasonForChange`
The decision to omit these extra metadata fields from collection endpoints was intentional, in the interest of keeping bulk responses …
> Extra metadata

- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers/internal.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/util/data_compilation.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/util/data_validation.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/util/data_compilation_test.clj
Tablecloth guesses the column types based on values present in the dataset. If we have a column with one row and value 75, in a column where we expect a floating point value, the column type will be int.
This change updates the `as-dataset` function to optionally take a `:convert-types` option (along with DataseRow) to do the conversion.
> ensure dataset column types match the ones in Release schema

- datahost-ld-openapi/env/test/resources/test-system.edn
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
The GET RELEASE endpoint now can return 422 when the release has no
revisions (and changes), as there's nothing to redirect to.
Some of the release specific tests were moved to revision test namespace
because of that.
Also: since we use the redirect URL, the rdf-base-uri can't be bogus
anymore (in test context).
Fixes #264
> ldapi: redirect to latest rev. when requesting release as text/csv

- datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/util/data_compilation.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/util/data_validation.clj
This PR replace some of the asserts with explicit throws where it makes sense.
The line [mentioned](https://github.com/Swirrl/datahost-prototypes/blob/af93a8b9d2927965b78982be36fa416444b099e7/datahost-ld-openapi/src/tpximpact/datahost/ldapi/util/data_validation.clj#L128) in the issue has been updated in #290 
Fixes #281
> Replace asserts with explicit throws

- datahost-ld-openapi/bin/hurl-data/hurl-gen.py
This is for reverse engineering the generation process if the hurl script needs to be changed
> Added a line to hurl-gen.py that copies the python arguments used to generate Hurl scripts.

- datahost-ld-openapi/src/tpximpact/datahost/ldapi/db.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj
- datahost-ld-openapi/src/tpximpact/datahost/system_uris.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_schema_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/resources.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/revision_test.clj
Closes #277 - Update the application routes to use the singular case to address individual resources e.g. a release now has a path of /{series-slug}/release/{release-slug}. Routes which return a collection of resources still use the plural case.
Rename 'change' to 'commit' within revision change routes. This is the first stage of an upcoming series of changes in terminology from 'change' to 'commit'. The rest of the code still widely refers to commits as changes to minimise the required changes here.
Update the implementation of the AppUri protocol to reflect the new URI structure for resources. Rename the change-uri(*) method(s) to commit-uri(*) and rename the api parameters change-id key to commit-id within commit-uri*.
Update all tests to use the new URIs.
WARNING: Do not merge this PR …
> Update application routes to use singular for individual resources

- datahost-ld-openapi/hurl-scripts/int-002.hurl
- datahost-ld-openapi/hurl-scripts/int-010.hurl
- datahost-ld-openapi/hurl-scripts/int-011.hurl
- datahost-ld-openapi/hurl-scripts/int-012.hurl
- datahost-ld-openapi/hurl-scripts/int-013.hurl
- datahost-ld-openapi/hurl-scripts/int-014.hurl
- datahost-ld-openapi/hurl-scripts/int-015.hurl
- datahost-ld-openapi/hurl-scripts/issue-282.hurl
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/handlers.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/router.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/middleware.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/release.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/shared.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/integration_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_schema_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/models/release_test.clj
- datahost-ld-openapi/test/tpximpact/datahost/ldapi/test_util/hurl.clj
Partially addresses issue https://github.com/Swirrl/datahost-prototypes/issues/184
Redirect Release route with accept header to CSV or JSON file route.
When a Release route receives an allowed `Accept: text/csv` it should not serve the content from its route but instead redirect users to the same file route with the `.csv` extension. Same for application/json (redirects with `.json` extension)
This PR is only the first step. The next step from the linked issue will be serving of the CSVW metadata itself:
_"In order to fullfill our obligations to the CSVW spec we should then also support the following route which is where we will map our datahost schema into CSVW."_
_`/data/dataset-series/release/:release-id.csv-metadata.json`_
> CSVW routes part 1: Release Accept header reoute redirects to file route

- datahost-ld-openapi/hurl-scripts/int-011.hurl
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/middleware.clj
- datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/release.clj
Accept text/csv resource redirect to the file route `/doc/foo/release/baz.csv` should be 302 (Found); not 308 (Permanent Redirect).
This also addresses odd Chrome / Edge behaviour when following the redirect where the Accept header is changed from `text/csv` to `application/json` on the fly, so the client ends up being served a CSV file containing JSON data.
> Accept text/csv resource redirect to file should be 302 (Found)
